package com.astix.rajtraderssfasales.DistributorSocuting.ScoutInterface;


import com.astix.rajtraderssfasales.DistributorSocuting.ScoutingModels.TblPotentialDistributorRetailersFeedBackDetails;

public interface InterfaceEditDistributorScoutingRetailerFeedBaclStoreSelectoin {
    public void fnCallActivityFeedbackDistributorRetailerStoreSelection(TblPotentialDistributorRetailersFeedBackDetails tblPotentialDistributorRetailersFeedBackDetails);

}
